
enum Tokens {RELOP = 256, ADDOP, MULOP, ANDOP, BEGIN_, BOOLEAN, END, ENDREDUCE,
	FUNCTION, INTEGER, IS, REDUCE, RETURNS, IDENTIFIER, INT_LITERAL ,CASE, 
	ENDCASE, IF, ELSE, ENDIF, OTHERS, REAL, THEN, WHEN, OROP, NOTOP, REAL_LITERAL,
	REMOP, ARROW, EXPOP, BOOL_LITERAL};